// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagaer.Models;

#nullable disable

namespace TaskManagaer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221109115214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("LAB.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 15,
                            Author = "BB",
                            Description = "gsgkdgk",
                            Email = "1234@gmail.com",
                            TaskName = "AA"
                        },
                        new
                        {
                            Id = 16,
                            Author = "dd",
                            Description = "gsgkdksgksggk",
                            Email = "567568@gmail.com",
                            TaskName = "BB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
